[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  SUPABASE_URL = "https://sdpjxnmzxgpsxovpbwnk.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkcGp4bm16eGdwc3hvdnBid25rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk4NTk5NDgsImV4cCI6MjEwNTQzNTk0OH0.vLfrhk_GI_xWWCPmFrIEr3z5kBOyOUUyDZiHhh8xHRs"
  SUPABASE_DATABASE_URL = "postgresql://postgres:chimuanya2001@db.sdpjxnmzxgpsxovpbwnk.supabase.co:5432/postgres"
  JWT_SECRET = "chimuanya2001"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
